Fix using `downcast` with `anyhow::Error` (#12689)
* Fix using `downcast` with `anyhow::Error`

Previously when converting `wasmtime::Error` into `anyhow::Error` it
ended up breaking the `downcast` method. This is because
`anyhow::Error::from_boxed` looks like it does not implement the
`downcast` method which is how all errors were previously converted to
`anyhow::Error`. This commit adds a new vtable method for specifically
converting to `anyhow::Error` which enables using the typed construction
methods of `anyhow` which preserves `downcast`-ness.

* Add a test showcasing anyhow-source behavior